### ISSUE TITLE
htaccess et RewriteRule

### ISSUE THREAD

**Issue by the2ne** [the2ne/the2ne.github.io#1]
Après plusieurs tentatives infructueuses, la redirection de `index.html` vers la racine ne fonctionne toujours pas et je dois bien avouer mes limites dans ce domaine (oui, comme dans beaucoup d'autres).

`RewriteCond %{THE_REQUEST} \ /(.+/)?index(\.html)?(\?.*)?\  [NC]`
`RewriteRule ^(.+/)?index(\.html)?$ /%1 [R=301,L]`

Si une âme charitable voulait bien me venir en aide pour résoudre ce problème.
@zeppelinlg @vuzonp une idée ?

**Comment by zeppelinlg** [comment]
Je verrais bien ça comme ça moi :

```
RewriteEngine  on
RewriteRule ^(.+/)?index\.html(.*)$ %1/%2 [R=301,L]
```

**Comment by the2ne** [comment]
la vérité est ailleurs :(

**Comment by the2ne** [comment]
Bon, j'ai la réponse. C'était pourtant simple.
L'hébergement sur les GitHub Pages a ses limites. On ne peut héberger que du contenu statique, pas de code qui s’exécute côté serveur et donc de htaccess qui modifierait leur config.

Je vais devoir passer au plan B plus tôt que prévu !
